#!/bin/sh

# Author : Dao Quoc Dai from Viet Nam - itvn9online@gmail.com

# update system
sudo apt-get update -y
sudo apt-get upgrade -y

# install firewall
sudo apt-get install -y fail2ban ufw

# SSH, HTTP and HTTPS
ufw allow 22
ufw allow 80
ufw allow 443

# FTP
ufw allow 21 
ufw allow 50000:50099/tcp 
ufw allow out 20/tcp

# And lastly we activate UFW
ufw --force enable

#
sudo apt-get -y install wget nano

#
cd ~
bash <( curl -k https://github.com/itvn9online/vpssim-ubuntu/raw/main/vpssim/menu/git-clone )

#
cd ~
cd /opt/echbay_vpssim
chmod +x setup
bash setup
