#!/bin/sh

# Author : Dao Quoc Dai - itvn9online@gmail.com

# update system
sudo apt-get update -y
sudo apt-get upgrade -y

# install firewall
sudo apt-get install -y fail2ban ufw

# SSH, HTTP and HTTPS
ufw allow 22
ufw allow 80
ufw allow 443

# And lastly we activate UFW
ufw --force enable

#
sudo apt-get -y install wget nano

#
cd ~
wget https://github.com/itvn9online/vpssim-ubuntu/raw/main/vpssim/menu/git-clone && chmod +x git-clone && bash git-clone

#
cd ~
cd /opt/echbay_vpssim
chmod +x setup
bash setup
