#!/bin/bash
. /home/vpssim.conf

#
echo "Install MariaDB..."
sleep 2

#
cd ~

#
DATABASE_PASS=$mariadbpass

#Set up MariaDB repositories
apt-key adv --fetch-keys 'https://mariadb.org/mariadb_release_signing_key.asc'
add-apt-repository 'deb [arch=amd64,arm64,ppc64el] http://mirror.netinch.com/pub/mariadb/repo/10.3/ubuntu focal main'


#Install MariaDB (MySQL) and set a strong root password
apt-get install -y mariadb-server;


#
mysqladmin -u root password "$DATABASE_PASS"
# Make sure that NOBODY can access the server without a password
mysql -u root -p"$DATABASE_PASS" -e "UPDATE mysql.user SET Password=PASSWORD('$DATABASE_PASS') WHERE User='root'"
# Kill the anonymous users
mysql -u root -p"$DATABASE_PASS" -e "DELETE FROM mysql.user WHERE User='root' AND Host NOT IN ('localhost', '127.0.0.1', '::1')"
mysql -u root -p"$DATABASE_PASS" -e "DELETE FROM mysql.user WHERE User=''"
# Kill off the demo database
mysql -u root -p"$DATABASE_PASS" -e "DELETE FROM mysql.db WHERE Db='test' OR Db='test\_%'"
# Make our changes take effect
mysql -u root -p"$DATABASE_PASS" -e "FLUSH PRIVILEGES"
