#!/bin/bash
. /home/vpssim.conf

#
echo "Install Nginx"
sleep 2

#
sudo apt install nginx -y
sudo systemctl enable nginx
sudo systemctl start nginx

sudo iptables -I INPUT -p tcp --dport 80 -j ACCEPT
sudo ufw allow http

sudo chown www-data:www-data /usr/share/nginx/html -R
sudo chown www-data:www-data /var/www/ -R



#Tweak Nginx settings
yes | cp -rf /opt/echbay_vpssim/vpssim/conf/nginx.conf /etc/nginx/nginx.conf

sed -i "s/worker_processes.*/worker_processes auto;/" /etc/nginx/nginx.conf
sed -i "s/# multi_accept.*/multi_accept on;/" /etc/nginx/nginx.conf
sed -i "s/# server_names_hash_bucket_size.*/server_names_hash_bucket_size 128;/" /etc/nginx/nginx.conf
sed -i "s/# server_tokens off/server_tokens off/" /etc/nginx/nginx.conf

# disable nginx log
sed -i "s/access_log.*/access_log off;/" /etc/nginx/nginx.conf
sed -i "s/error_log.*/error_log off;/" /etc/nginx/nginx.conf

#Configure Gzip for Nginx
yes | cp -rf /opt/echbay_vpssim/vpssim/conf/gzip.conf /etc/nginx/conf.d/gzip.conf
