#!/bin/bash


#Add some PPAs to stay current
#apt-get install -y software-properties-common
#apt-add-repository ppa:ondrej/apache2 -y
#apt-add-repository ppa:ondrej/nginx-mainline -y
#apt-add-repository ppa:ondrej/php -y

#Set up MariaDB repositories
apt-key adv --fetch-keys 'https://mariadb.org/mariadb_release_signing_key.asc'
add-apt-repository 'deb [arch=amd64,arm64,ppc64el] http://mirror.netinch.com/pub/mariadb/repo/10.3/ubuntu focal main'

#Install base packages
apt-get update; apt-get install -y build-essential curl nano wget lftp unzip bzip2 arj nomarch lzop htop openssl gcc git binutils libmcrypt4 libpcre3-dev make python3 python3-pip supervisor unattended-upgrades whois zsh imagemagick uuid-runtime net-tools

#Set the timezone to UTC
ln -sf /usr/share/zoneinfo/UTC /etc/localtime
