#!/bin/bash


#Add some PPAs to stay current
#apt-get install -y software-properties-common
#apt-add-repository ppa:ondrej/apache2 -y
#apt-add-repository ppa:ondrej/nginx-mainline -y
#apt-add-repository ppa:ondrej/php -y

#Set up MariaDB repositories
apt-key adv --fetch-keys 'https://mariadb.org/mariadb_release_signing_key.asc'
add-apt-repository 'deb [arch=amd64,arm64,ppc64el] http://mirror.netinch.com/pub/mariadb/repo/10.3/ubuntu focal main'

#Install base packages
sudo apt-get -y update
sudo apt-get install -y build-essential curl nano wget lftp unzip bzip2 arj nomarch lzop htop openssl gcc git binutils libmcrypt4 libpcre3-dev make python3 python3-pip supervisor unattended-upgrades whois zsh imagemagick uuid-runtime net-tools

#Set the timezone to UTC
ln -sf /usr/share/zoneinfo/UTC /etc/localtime


# install nginx
sudo apt install nginx -y
sudo systemctl enable nginx
sudo systemctl start nginx

sudo iptables -I INPUT -p tcp --dport 80 -j ACCEPT
sudo ufw allow http

sudo chown www-data:www-data /usr/share/nginx/html -R
sudo chown www-data:www-data /var/www/ -R


#Install PHP7.4 and common PHP packages
echo "Install PHP 7.4"

sudo apt install -y php7.4 php7.4-fpm php7.4-mysql php-common php7.4-cli php7.4-common php7.4-json php7.4-opcache php7.4-readline php7.4-mbstring php7.4-xml php7.4-gd php7.4-curl


sudo systemctl enable php7.4-fpm
sudo systemctl start php7.4-fpm
